set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p')

if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif

set nocompatible
filetype off

set rtp+=$XDG_CONFIG_HOME/vim/bundle/Vundle.vim
call vundle#begin('$XDG_CONFIG_HOME/vim/bundle')
Plugin 'prabirshrestha/async.vim'
Plugin 'prabirshrestha/vim-lsp'

Plugin 'prabirshrestha/asyncomplete.vim'
Plugin 'prabirshrestha/asyncomplete-lsp.vim'
Plugin 'keremc/asyncomplete-clang.vim'

Plugin 'sheerun/vim-polyglot'
Plugin 'bfrg/vim-cpp-modern'

Plugin 'vimwiki/vimwiki'

Plugin 'morhetz/gruvbox'

call vundle#end()
filetype plugin indent on

" GENERAL SETTING

" File settings
set encoding=utf8
set autoread
set syntax=on

" Spelling
set spell
set spelllang=en_us
set spellsuggest=fast,20


" Key remaps
let g:mapleader="\<space>"
noremap - :w<CR>:TestNearest<CR>

" Disable arrow keys
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
nnoremap <up> <nop>

" Editor look and feel
set cursorline
set history=10000
set incsearch
set list listchars=tab:\ \ ,trail:.
set nowrap

let &t_ZH="\e[3m"
let &t_ZR="\e[23m"

set t_Co=256
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors

" Search
set hlsearch
set ignorecase
set incsearch
set smartcase

" Tabs and Spaces
set tabstop=4   " maximum width of actual tab character
set softtabstop=4
set shiftwidth=4  " the size of an indent
set expandtab     " insert spaces instead of a tab character

" Panes
set splitbelow
set splitright

" Set command menu
set showcmd
set wildmenu
set wildmode=full

" Set line numbers
:set number relativenumber
:augroup numbertoggle
: autocmd!
: autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
: autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
:augroup END

highlight Visual ctermfg=yellow ctermbg=gray

source <sfile>:h/clangd.vim
source <sfile>:h/gruvbox.vim
source <sfile>:h/hex.vim
source <sfile>:h/wiki.vim
