#
# ${XDG_CONFIG_HOME}/bash/bash_profile
#

export VIM_HOME="$XDG_CONFIG_HOME/vim"

export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc

export GVIMINIT='let $MYGVIMRC="$VIM_HOME/gvimrc" | source $MYGVIMRC'
export VIMINIT='let $MYVIMRC="$VIM_HOME/vimrc" | source $MYVIMRC'

export GNUPGHOME="$XDG_DATA_HOME/gnupg"

export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass-store"
export PASSWORD_STORE_ENABLE_EXTENSIONS=true
export PASSWORD_STORE_EXTENSIONS_DIR="$XDG_DATA_HOME/pass-store/.extensions"

export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export LYNX_CFG="$XDG_CONFIG_HOME/lynx.cfg"

export PATH=$HOME/bin:$PATH
