#
# ${XDG_CONFIG_HOME}/bash/bash_profile
#

export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthorit
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc

export GVIMINIT='let $MYGVIMRC="$XDG_CONFIG_HOME/vim/gvimrc" | source $MYGVIMRC'
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass-store"
export PASSWORD_STORE_ENABLE_EXTENSIONS=true
export PASSWORD_STORE_EXTENSIONS_DIR=/usr/local/lib/password-store/extensions

export WGETRC="$XDG_CONFIG_HOME/wgetrc"
