#
# ${XDG_CONFIG_HOME}/bash/bash_profile
#

export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthorit
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc

export GVIMINIT='let $MYGVIMRC="$XDG_CONFIG_HOME/vim/gvimrc" | source $MYGVIMRC'
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
